---
name: Pull request review and mention bot using OpenCode
on:
  pull_request:
    types:
      - opened
      - ready_for_review
  issue_comment:
    types:
      - created
  pull_request_review_comment:
    types:
      - created
  issues:
    types:
      - opened
      - assigned
permissions:
  contents: read
jobs:
  opencode-review:
    if: >
      github.event_name == 'pull_request'
      && contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.pull_request.author_association)
      && (! github.event.pull_request.draft)
      && (! startsWith(github.head_ref, 'dependabot/'))
      && (! startsWith(github.head_ref, 'renovate/'))
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    uses: ./.github/workflows/opencode-review.yml
    with:
      model: sakura/preview/Kimi-K2.7-Code
    secrets: inherit
  opencode-bot:
    if: >
      (
        (github.event_name == 'issue_comment' || github.event_name == 'pull_request_review_comment')
        && contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.comment.author_association)
        && (
          startsWith(github.event.comment.body, '/oc')
          || contains(github.event.comment.body, ' /oc')
          || startsWith(github.event.comment.body, '/opencode')
          || contains(github.event.comment.body, ' /opencode')
        )
      ) || (
        github.event_name == 'issues'
        && contains(fromJSON('["OWNER","MEMBER","COLLABORATOR"]'), github.event.issue.author_association)
        && (
          (contains(github.event.issue.body, '/oc') || contains(github.event.issue.title, '/oc'))
          || (contains(github.event.issue.body, '/opencode') || contains(github.event.issue.title, '/opencode'))
        )
      )
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    uses: ./.github/workflows/opencode-bot.yml
    with:
      model: sakura/preview/Kimi-K2.7-Code
    secrets: inherit
